### ISSUE TITLE
Make sure that everything's working (Shaun)

### ISSUE THREAD

**Issue by sgolodetz** [sgolodetz/game1666#5]
As with the issue I just submitted for Jonny, probably worth checking that you can fetch upstream updates from my repo.

**Comment by berkano** [comment]
successfully cloned & tested pulling updates!

**Comment by sgolodetz** [comment]
Good work! :) Make sure that you push the updates to your GitHub repository btw (git push origin dev) - it looks like you've pulled onto your local computer at the moment but the one on GitHub is still outdated.
